task_map = {
    'Classification': ('Classification', 'deepghs/anime_classification', 'mobilenetv3_v1.3_dist'),
    'Monochrome': ('Monochrome', 'deepghs/monochrome_detect', 'mobilenetv3_large_100_dist'),
    'Completeness': ('Completeness', 'deepghs/anime_completeness', 'mobilenetv3_v2.2_dist'),
    'AI Check': ('AI Check', 'deepghs/anime_ai_check', 'mobilenetv3_sce_dist'),
    'AI Corrupt': ('AI Corrupt', 'deepghs/ai_image_corrupted', 'caformer_s36_v0_focal'),
    'Rating': ('Rating', 'deepghs/anime_rating', 'mobilenetv3_sce_dist'),
    'Character Sex': ('Character Sex', 'deepghs/anime_ch_sex', 'caformer_s36_v1'),
    'Portrait Type': ('Portrait Type', 'deepghs/anime_portrait', 'mobilenetv3_v0_dist'),
    'Age of Style': ('Age of Style', 'deepghs/anime_style_ages', 'mobilenetv3_v0_dist'),
    'Bangumi Portrait': ('Bangumi Portrait', 'deepghs/bangumi_char_type', 'mobilenetv3_v0_dist'),
    'Is That Anime?': ('Is That Anime?', 'deepghs/anime_real_cls', 'mobilenetv3_v1.2_dist'),
    'Teen': ('Teen', 'deepghs/anime_teen', 'caformer_s36_v0'),
    'Character Skin': ('Character Skin', 'deepghs/anime_ch_skin_color', 'caformer_s36'),
    'Character Hair Color': ('Character Hair Color', 'deepghs/anime_ch_hair_color', 'caformer_s36_v0'),
    'Character Eye Color': ('Character Eye Color', 'deepghs/anime_ch_eye_color', 'caformer_s36_v0'),
    'Character Hair Length': ('Character Hair Length', 'deepghs/anime_ch_hair_length', 'caformer_s36_v0'),
    'Character Ears': ('Character Ears', 'deepghs/anime_ch_ear', 'caformer_s36_v0'),
    'Character Horns': ('Character Horns', 'deepghs/anime_ch_horn', 'caformer_s36_v0'),
    '[Beta] Danbooru Rating': ('[Beta] Danbooru Rating', 'deepghs/anime_dbrating', 'mobilenetv3_large_100_v0_ls0.2'),
    '[Beta] Danbooru Aesthetic': ('[Beta] Danbooru Aesthetic', 'deepghs/anime_aesthetic', 'caformer_s36_v0_ls0.2'),
}


repo_models = {
    'deepghs/anime_classification': ['caformer_s36', 'caformer_s36_plus', 'caformer_s36_v1', 'caformer_s36_v1.1_focal', 'caformer_s36_v1.2_focal', 'caformer_s36_v1.3_focal', 'caformer_s36_v1.4_focal', 'caformer_s36_v1.4_focal_fp32', 'mobilenetv3', 'mobilenetv3_dist', 'mobilenetv3_sce', 'mobilenetv3_sce_dist', 'mobilenetv3_v1.2_dist', 'mobilenetv3_v1.3_dist', 'mobilenetv3_v1.4_dist', 'mobilenetv3_v1_dist', 'mobilevitv2_150'],
    'deepghs/monochrome_detect': ['caformer_s36', 'caformer_s36_plus', 'caformer_s36_plus_safe2', 'caformer_s36_safe2', 'mobilenetv3_large_100', 'mobilenetv3_large_100_dist', 'mobilenetv3_large_100_dist_safe2', 'mobilenetv3_large_100_safe2'],
    'deepghs/anime_completeness': ['caformer_s36_v0', 'caformer_s36_v0_c_sce', 'caformer_s36_v1', 'caformer_s36_v2', 'caformer_s36_v2-beta', 'caformer_s36_v2.1', 'caformer_s36_v2.2', 'mobilenetv3_v2.1_dist', 'mobilenetv3_v2.2_dist', 'mobilenetv3_v2_dist'],
    'deepghs/anime_ai_check': ['caformer_s36_plus_sce', 'caformer_s36_sce_v1', 'mobilenetv3_sce', 'mobilenetv3_sce_dist', 'mobilenetv3_sce_dist_v1'],
    'deepghs/ai_image_corrupted': ['caformer_s36_v0_focal', 'caformer_s36_v0_sce', 'mobilenetv3_v0_focal_dist'],
    'deepghs/anime_rating': ['caformer_b36_v1_pruned_ls0.1', 'caformer_s36_plus', 'caformer_s36_v1_pruned_ls0.1', 'mobilenetv3', 'mobilenetv3_sce', 'mobilenetv3_sce_dist', 'mobilenetv3_v1_pruned_ls0.1'],
    'deepghs/anime_ch_sex': ['caformer_s36', 'caformer_s36_v1', 'caformer_s36_v1.1_noconfuse', 'caformer_s36_v1_noconfuse', 'mobilenetv3_v1.1_noconfuse_dist'],
    'deepghs/anime_portrait': ['caformer_s36_v0', 'mobilenetv3_small_v0_dist', 'mobilenetv3_v0_dist'],
    'deepghs/anime_style_ages': ['caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/bangumi_char_type': ['caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/anime_real_cls': ['caformer_s36_v0', 'caformer_s36_v1', 'caformer_s36_v1.1', 'caformer_s36_v1.1_ls0.1', 'caformer_s36_v1.2', 'caformer_s36_v1.3', 'caformer_s36_v1.3_fp32', 'caformer_s36_v1.3_ls0.1', 'caformer_s36_v1_ls0.1', 'mobilenetv3_v0_dist', 'mobilenetv3_v1.1_dist_ls0.1', 'mobilenetv3_v1.2_dist', 'mobilenetv3_v1.3_dist', 'mobilenetv3_v1_dist_ls0.1'],
    'deepghs/anime_teen': ['caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/anime_ch_skin_color': ['caformer_s36', 'mobilenetv3_v0_dist'],
    'deepghs/anime_ch_hair_color': ['caformer_s36_raw', 'caformer_s36_v0', 'caformer_s36_v0_ncerce', 'mobilenetv3_v0_dist'],
    'deepghs/anime_ch_eye_color': ['caformer_s36_raw', 'caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/anime_ch_hair_length': ['caformer_s36_raw', 'caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/anime_ch_ear': ['caformer_s36_raw', 'caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/anime_ch_horn': ['caformer_s36_raw', 'caformer_s36_v0', 'mobilenetv3_v0_dist'],
    'deepghs/anime_dbrating': ['caformer_s36_v0_ls0.2', 'mobilenetv3_large_100_v0_ls0.2', 'swinv2pv3_v0_ls0.2'],
    'deepghs/anime_aesthetic': ['caformer_s36_v0_ls0.2', 'swinv2pv3_v0_448_ls0.2', 'swinv2pv3_v0_448_ls0.2_x']
}